nixit: extract core logic from `nixos-rebuild switch`

diff --git a/nixit b/nixit
--- a/nixit
+++ b/nixit
@@ -9,3 +9,18 @@ set -euo pipefail
 # FIXME: create symlinks (see `home-manager switch`)
 # TODO: LATER: install itself in /usr/sbin/nixit
 # FIXME: activate/restart/reload systemd services (see `nixos-rebuild switch`, maybe also `home-manager switch`)
+
+# nixos-rebuild does:
+#
+#     echo "building the system configuration..." >&2
+#     if [ "$action" = switch -o "$action" = boot ]; then
+#         pathToConfig="$(nixBuild '<nixpkgs/nixos>' --no-out-link -A system "${extraBuildFlags[@]}")"
+#         copyToTarget "$pathToConfig"
+#         targetHostCmd nix-env -p "$profile" --set "$pathToConfig"
+#     fi
+#
+#     if ! targetHostCmd $pathToConfig/bin/switch-to-configuration "$action"; then
+#         echo "warning: error(s) occurred while switching to the new configuration" >&2
+#         exit 1
+#     fi
+
